### ISSUE TITLE
修改cacctmgr show users/accounts 输出，改成树状结构，或者表格形式

### ISSUE THREAD

**Issue by Ashlee1994** [PKUHPC/Crane#32]

**Comment by Ashlee1994** [comment]
![Image](https://user-images.githubusercontent.com/23020681/192953327-98cda9ce-e83a-4caa-940c-57e2f651c4bd.png)

**Comment by MCKZX-llx** [comment]
![Image](https://user-images.githubusercontent.com/52701958/194453211-275d2eb8-960d-4109-998c-10df032796e6.jpg)



![Image](https://user-images.githubusercontent.com/52701958/194456998-1a2473f6-d216-4adf-8708-19f8f5e54e7a.jpg)
