### ISSUE TITLE
在北京大学高性能计算平台提交一个gpu作业

### ISSUE THREAD

**Issue by Ashlee1994** [PKUHPC/Crane#47]

**Comment by Ashlee1994** [comment]
根据https://hpc.pku.edu.cn/_book/guide/access/access.html 教程，首先绑定二次认证的秘钥，然后ssh 登录wm1-login.pku.edu.cn。


根据教程：https://hpc.pku.edu.cn/_book/guide/slurm/sbatch.html 中的GPU例子，在北京大学未名一号集群上提交一个GPU作业，

**Comment by Gxy-2001** [comment]
![Image](https://user-images.githubusercontent.com/56917631/196608745-342f786c-a10f-481f-9e91-5c0fbbdbd8bc.png)
![Image](https://user-images.githubusercontent.com/56917631/196608746-ea9b5179-9f0a-443a-ad2c-342b323592d9.jpg)
