### ISSUE TITLE
根据cacctmgr的help撰写方式，进行cbatch,ccontrol的help撰写

### ISSUE THREAD

**Issue by Ashlee1994** [PKUHPC/Crane#49]

**Comment by June19980** [comment]
![Image](https://user-images.githubusercontent.com/38131405/198232228-9e30a1c0-0ab2-413d-9e8f-6112258f51a8.png)

**Comment by June19980** [comment]
![image](https://user-images.githubusercontent.com/38131405/198879358-6f66e975-04b5-4e88-b57a-f74710493af2.png)
