### ISSUE TITLE
根据cacctmgr的help撰写方式，进行ccancel,cqueue的help撰写

### ISSUE THREAD

**Issue by Ashlee1994** [PKUHPC/Crane#50]

**Comment by June19980** [comment]
![Image](https://user-images.githubusercontent.com/38131405/197313048-1d292547-f9e0-415f-8c5d-e3c10905efaf.jpg)

**Comment by June19980** [comment]
![60e78819113933c64f378010455ce93](https://user-images.githubusercontent.com/38131405/197350421-45189ef2-926e-4680-aa95-e0cc72027bd6.png)
