### ISSUE TITLE
完善cqueue的功能，包括-h,-i,-j,-l,-n,-q,--start,-t,-o,-u,-A

### ISSUE THREAD

**Issue by Ashlee1994** [PKUHPC/Crane#56]
在测试集群中按照下列截图方式测试，并完成功能

**Comment by Ashlee1994** [comment]
-h 表示不显示作业表头


![Image](https://user-images.githubusercontent.com/23020681/199410832-fea714a5-68d9-4976-8af5-292c4dcf8fde.png)

**Comment by Ashlee1994** [comment]
squeue -i 1 或者 squeue --iterate 1 表示每1秒刷新输出,-i 后面参数表示间隔秒
![image](https://user-images.githubusercontent.com/23020681/199411280-e7486977-eca3-43f6-a845-0c2460fd3a64.png)

**Comment by Ashlee1994** [comment]
查看某个或某几个特定作业
![image](https://user-images.githubusercontent.com/23020681/199411529-ac46cb75-2f10-4708-abfd-221d8cb812f6.png)

**Comment by Ashlee1994** [comment]
squeue -l 显示更多作业信息
![image](https://user-images.githubusercontent.com/23020681/199411696-a583df77-fe9f-4204-a849-fb2ac5375eff.png)

**Comment by Ashlee1994** [comment]
squeue -n hello 过滤作业名为hello的所有作业
![image](https://user-images.githubusercontent.com/23020681/199411879-d2e0cd0c-154b-478c-97a6-d8935b3f27d8.png)

**Comment by Ashlee1994** [comment]
squeue -q low 过滤所有qos为low的作业
![image](https://user-images.githubusercontent.com/23020681/199412200-1e9c4154-4597-4daa-8c1e-d07c4c4f22c0.png)

**Comment by Ashlee1994** [comment]
squeue --start 显示排队中的作业的预期执行时间
![image](https://user-images.githubusercontent.com/23020681/199412644-fbffef4b-ac88-4917-ae99-a3f7f7b232e7.png)

**Comment by Ashlee1994** [comment]
squeue -t PD 显示正在排队的所有作业，R或者RUNNING显示正在运行的作业
![image](https://user-images.githubusercontent.com/23020681/199412885-3f447c43-533a-4538-a43b-ae047f56b524.png)

**Comment by Ashlee1994** [comment]
squeue -o "%.18i %.9P %.8j %.8q %.12u %.8T %.10M %.9l %.6D %R" 按照格式显示作业信息，具体每个格式的意思查看SLURM用户手册第19页到21页
![image](https://user-images.githubusercontent.com/23020681/199413124-b0786ed9-d249-4725-8fa0-63b83d181722.png)

**Comment by June19980** [comment]
cqueue -n 不显示表头的输出
![image](https://user-images.githubusercontent.com/38131405/200581635-470e6fa0-9779-4e3b-9067-171e538cf10c.png)

**Comment by June19980** [comment]
cqueue -i 自定义间隔时间（秒）输出
![image](https://user-images.githubusercontent.com/38131405/200581874-4038ebfa-1ab7-4226-b116-c3588e534e8f.png)

**Comment by Ashlee1994** [comment]
这些测试数据都在真实提交了作业之后有作业的情况下测试一下

**Comment by Ashlee1994** [comment]
cqueue -o的每一项设定一个最大长度，TaskId 长度最大15位，Type最大15位，Status最大15位，NodeIndex最大50位，有了最大长度之后，就需要 %.18j这种情况按格式输出长度，后续NodeIndex、JobName、Reason这些值都有可能超过50

**Comment by Ashlee1994** [comment]
cqueue仅输出running，pending，cancelling，completing作业

**Comment by Ashlee1994** [comment]
cqueue -u xiaojun
仅输出xiaojun用户的所有作业，输出按照cqueue的默认格式输出

**Comment by Ashlee1994** [comment]
cqueue能够通过-o指定输出下列选项：
1. jobId
2. 分区名
3. 作业名称
4. 用户名
5. 作业的状态
6. 已使用的时间
7. 分配给作业的节点数或挂起作业所需的最小节点数
8. 对于正常状态的作业, 显示分配节点的列表. 对于挂起或失败的作业, 需要显示原因
9. 作业相关的账户
10. 作业请求的cpu数量或者实际分配给它的cpu数量
11. qos 
12. 作业的提交时间
13. 对于挂起的作业, 将被用到的节点
14. 作业时间限制
15. 工作目录
